### ISSUE TITLE
Library incompatibility with Atmega 8

### ISSUE THREAD

**Issue by varshu** [shirriff/Arduino-IRremote#104]
I was compiling the code on 'arduino NG or older w/ atmega8' and I got the following error. 
![capture](https://cloud.githubusercontent.com/assets/6443843/5887828/90f63d0a-a40b-11e4-917e-8b987675a769.PNG)

The code: 

![image](https://cloud.githubusercontent.com/assets/6443843/5887875/8238b430-a40d-11e4-9277-6e3041e722f7.png)

The code runs in Arduino UNO. How to fix this? How to make the library work for Atmega 8?

**Comment by joshuajnoble** [comment]
This seems to indicate that the program is too large to fit in the program space afforded by the Atmega 8. I wonder if it would fit if you modify the library to remove all the defines and info for remotes other than the one that you're using.

**Comment by z3t0** [comment]
@varshu Issue will be closed as this is a board dependent issue, and the board does not have enough memory space to load this library. 
**Possible Solution**: Remove defines in the library that are unneeded to try and make the library small enough to fit on the board.

**Comment by christophe94700** [comment]
it can be used with a Atmega8. I deleted the protocols that I do not use the IRremote.h file.
example:
I use only:

#define DECODE_NEC 1
#define SEND_NEC 1

#define DECODE_SAMSUNG 1
#define SEND_SAMSUNG 1

**Comment by z3t0** [comment]
awesome glad it worked
