### ISSUE TITLE
IRrecvDemo won't complie

### ISSUE THREAD

**Issue by TheMabb** [shirriff/Arduino-IRremote#112]
I try to compile the demo and I get this:

Arduino: 1.6.1 (Windows 8.1), Board: "Arduino Uno"

C:\Program Files (x86)\Arduino\libraries\IRremote\IRremote.cpp: In member function 'long int IRrecv::decodeWhynter(decode_results*)':

C:\Program Files (x86)\Arduino\libraries\IRremote\IRremote.cpp:753:51: error: a function-definition is not allowed here before '{' token

 long IRrecv::decodeSharp(decode_results *results) {

                                                   ^

C:\Program Files (x86)\Arduino\libraries\IRremote\IRremote.cpp:1357:1: error: expected '}' at end of input

 }

 ^

C:\Program Files (x86)\Arduino\libraries\IRremote\IRremote.cpp:1357:1: error: expected '}' at end of input

Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by z3t0** [comment]
Thank you for the detailed report. I'll get on it :smile:

**Comment by z3t0** [comment]
What version of the library are you using? 1.0 or 1.0.1 It seems as though you are using 1.0.1 which is a beta release. Please make sure you are using the latest [stable](https://github.com/shirriff/Arduino-IRremote/releases/tag/MAJOR) release.

Thank you for reporting that error. It really helps for further development.

**Comment by TheMabb** [comment]
You are absolutely right I was using 1.0.1. My bad. Thanks!

**Comment by z3t0** [comment]
No problem, Thank YOU for reporting the bug. We are now one step closer to adding new features to the main repo. :+1:
