### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by mudbug765** [shirriff/Arduino-IRremote#115]
I get the following error when attempting to compile the program IRrecvDemo...
C:\Program Files (x86)\Arduino\libraries\RobotIRremote\src\IRremoteTools.cpp:5:16: error: 'TKD2' was not declared in this scope
 int RECV_PIN = TKD2; // the pin the IR receiver is connected to

Error compiling.

Any suggestions?
Thanks,
Doug

**Comment by z3t0** [comment]
#98 Please check there
