### ISSUE TITLE
Problem with Arduino Leonardo?

### ISSUE THREAD

**Issue by bschaeffner** [shirriff/Arduino-IRremote#12]
I want to use the Arduino Leonardo with the IRRemote Code but i became this error: 

In file included from C:\Program Files\ARDUINO\arduino-1.0.1-windows\libraries\IRremote\IRremote.cpp:17:
C:\Program Files\ARDUINO\arduino-1.0.1-windows\libraries\IRremote\/IRremoteInt.h:331:2: error: #error "Please add OC4A pin number here\n"
C:\Program Files\ARDUINO\arduino-1.0.1-windows\libraries\IRremote\IRremote.cpp: In member function 'void IRsend::enableIROut(int)':
C:\Program Files\ARDUINO\arduino-1.0.1-windows\libraries\IRremote\IRremote.cpp:252: error: 'TIMER_PWM_PIN' was not declared in this scope

I use Arduino 1.0.1 and with an uno or an Duamilanove it works fine. I can reproduse this with all examples of the IRRemote Library.

**Comment by auspex-nl** [comment]
Probably too old an issue, but I got a cheap sparkfun pro micro clone which lacks a pin 13 too.
I fixed it by changing a couple lines in IRremoteInt.h to make it use Timer 3 & pin 5:

```
// Teensy 2.0
#elif defined(__AVR_ATmega32U4__)
  //#define IR_USE_TIMER1   // tx = pin 14
  #define IR_USE_TIMER3   // tx = pin 9
  //#define IR_USE_TIMER4_HS  // tx = pin 10
```
and

```
// defines for timer3 (16 bits)
#elif defined(IR_USE_TIMER3)
#define TIMER_RESET
#define TIMER_ENABLE_PWM     (TCCR3A |= _BV(COM3A1))
#define TIMER_DISABLE_PWM    (TCCR3A &= ~(_BV(COM3A1)))
#define TIMER_ENABLE_INTR    (TIMSK3 = _BV(OCIE3A))
#define TIMER_DISABLE_INTR   (TIMSK3 = 0)
#define TIMER_INTR_NAME      TIMER3_COMPA_vect
#define TIMER_CONFIG_KHZ(val) ({ \
  const uint16_t pwmval = SYSCLOCK / 2000 / (val); \
  TCCR3A = _BV(WGM31); \
  TCCR3B = _BV(WGM33) | _BV(CS30); \
  ICR3 = pwmval; \
  OCR3A = pwmval / 3; \
})
#define TIMER_CONFIG_NORMAL() ({ \
  TCCR3A = 0; \
  TCCR3B = _BV(WGM32) | _BV(CS30); \
  OCR3A = SYSCLOCK * USECPERTICK / 1000000; \
  TCNT3 = 0; \
})
//#if defined(CORE_OC3A_PIN)
//#define TIMER_PWM_PIN        CORE_OC3A_PIN  /* Teensy */
//#elif defined(__AVR_ATmega1280__) || defined(__AVR_ATmega2560__)
#define TIMER_PWM_PIN        5  /* Arduino Mega */
//#else
//#error "Please add OC3A pin number here\n"
//#endif
```

I can now send IR commands with a IR led on pin 5. Hope this helps anyone with a similar board.

**Comment by S01den** [comment]
Hi, i try this for my ardunio esplora (who has a ATmega32U4 like the leonardo), but it doesn't work, and the RGB LED integred light in red, instead of the IR led connected of the pin 3 (see http://pighixxx.com/esplorapdf.pdf )
the code is: 
`#include <Esplora.h>
#include <IRremote.h>

IRsend irsend;

void setup()
{
  
}

void loop()
{
  if (Esplora.readButton(SWITCH_LEFT) == LOW) {
      for (int i = 0; i < 1; i++) {
        irsend.sendNEC(0x77E190CB, 32); 
        delay(40);
  }
}`
 
however, when i do that:
`#include <Esplora.h>
#include <IRremote.h>

IRsend irsend;

void setup()
{
  pinMode(3, OUTPUT);
}

void loop()
{
 digitalWrite(3, HIGH);
}`

the led connected of the pin 3 lights, and not the RGB Led integrated.

P.S: Sorry for my english, I'm a french student.

**Comment by AnalysIR** [comment]
**First**, you should really open a new issue vs causing confusion and uneccessary overhead.

**Second**, you should place code inside code tags **<>**, from the edit menu bar. Please edit your previous post and correct.

**Third**, for Leonardo the default Tx pin is 13....so try that. If it doesn't work, you may have to change the timer used in boardefs.h. The pin mapping is avail able in the readme, here!
