### ISSUE TITLE
Send Types

### ISSUE THREAD

**Issue by ax5bm10** [shirriff/Arduino-IRremote#131]
Send Types those defined in the file IRremote.h are not defining functions IRSend class which causes an error in the arduino ide

**Comment by SpotComms** [comment]
Same here
![The error](https://i.imgur.com/Z45H7UT.png)

**Comment by ax5bm10** [comment]
#define SEND_NEC
#define SEND_SONY
#define SEND_RC5
#define SEND_RC6
#define SEND_DISH
#define SEND_SHARP
#define SEND_PANASONIC
#define SEND_JVC
#define SEND_SANYO
#define SEND_MITSUBISHI
#define SEND_SAMSUNG
#define SEND_RAW

to work, these definitions to be used

**Comment by SpotComms** [comment]
I'll redact my comment then since its completely unrelated to this issue.

**Comment by z3t0** [comment]
I'm assuming this has been solved? Please read the README.md.
