### ISSUE TITLE
Unknonw (Uncategorized) library category

### ISSUE THREAD

**Issue by slavkoja** [shirriff/Arduino-IRremote#133]
Library category in the library.properteis is "infrared", but by the Arduino library specification (https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification - i don't found one for 1.6 IDE), there is not infrared category.

I suggest to use the "Signal Input/Output", to prevent warnings when Arduino IDE starts.

regards

**Comment by z3t0** [comment]
@slavkoja Thanks for letting us know, will fix right now.

**Comment by z3t0** [comment]
Fixed in commit above
