### ISSUE TITLE
compiler error with IRSend Demo

### ISSUE THREAD

**Issue by redruff** [shirriff/Arduino-IRremote#135]
I know this has come up a few times, but...

I get this with the send demo, it is the stock code right from the Examples folder.
```
Arduino: 1.6.3 (Windows 7), Board: "Arduino Uno"
Build options changed, rebuilding all
IRrecord.ino: In function 'void sendCode(int)':
IRrecord.ino:103:14: error: 'class IRsend' has no member named 'sendNEC'
IRrecord.ino:107:14: error: 'class IRsend' has no member named 'sendNEC'
IRrecord.ino:113:12: error: 'class IRsend' has no member named 'sendSony'
IRrecord.ino:128:14: error: 'class IRsend' has no member named 'sendRC5'
IRrecord.ino:131:14: error: 'class IRsend' has no member named 'sendRC6'
Error compiling.
```
I have deleted all the RobotIR libraries, I only have the library "IRRemote" in the IDE library folder.
The REC demo works just fine. Is there a work around for this?

Here is the code throwing the error
```c
/*
 * IRremote: IRsendDemo - demonstrates sending IR codes with IRsend
 * An IR LED must be connected to Arduino PWM pin 3.
 * Version 0.1 July, 2009
 * Copyright 2009 Ken Shirriff
 * http://arcfn.com
 */

#include <IRremote.h>

IRsend irsend;

void setup()
{
  Serial.begin(9600);
}

void loop() {
  if (Serial.read() != -1) {
    for (int i = 0; i < 3; i++) {
      irsend.sendSony(0xa90, 12); // Sony TV power code
      delay(40);
    }
  }
}
```
Thanks in advance,
Red

**Comment by khair-eddine** [comment]
well if you write this code exactly, than you should write #include <IRremote.h> (on line1) instead of #include

**Comment by redruff** [comment]
not sure what happened there copy/paste error??

The include is there and correct in the IDE example.

/*
 * IRremote: IRsendDemo - demonstrates sending IR codes with IRsend
 * An IR LED must be connected to Arduino PWM pin 3.
 * Version 0.1 July, 2009
 * Copyright 2009 Ken Shirriff
 * http://arcfn.com
 */

#include <IRremote.h>

IRsend irsend;

void setup()
{
  Serial.begin(9600);
}

void loop() {
  if (Serial.read() != -1) {
    for (int i = 0; i < 3; i++) {
      irsend.sendSony(0xa90, 12); // Sony TV power code
      delay(40);
    }
  }
}

**Comment by redruff** [comment]
interesting..it whacks the "<IRremote.h>" probably thinks its HTML tags and gets crabby?

**Comment by khair-eddine** [comment]
oh yes i see, have you tried to unplug your board or restart sketch because i see no reason to error 
check it your library is written IRremote too because you writes IRRemote up

**Comment by redruff** [comment]
Thanks for all your help! Appreciate it!
I compared upper and lower case, they match. 
I cant get past the compiler error here, so it doesn't even go look for a board to download to.
Ya, I'm stumped on this one!

**Comment by khair-eddine** [comment]
you still have compiling problem ?

**Comment by z3t0** [comment]
please try the release version of the library, the repository is goin through refactoring as we work on multi ir support.

----- Reply message -----

**Comment by redruff** [comment]
where would one find the release version?
Yep Khair-eddine...I'm dead in the water right now.

**Comment by z3t0** [comment]
Sorry, would have linked you before but I was on my phone.
https://github.com/shirriff/Arduino-IRremote/releases

On Tue, Apr 28, 2015 at 3:49 PM, redruff <notifications@github.com> wrote:

> where would one find the release version?
> Yep Khair-eddine...I'm dead in the water right now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shirriff/Arduino-IRremote/issues/135#issuecomment-97236008>
> .
>



-- 
Thanks,
Rafi Khan

**Comment by khair-eddine** [comment]
hii bro, @z3t0 working on multi reception or emission ?

**Comment by redruff** [comment]
emmission, gonna give the release version a try in a minute.

**Comment by redruff** [comment]
oops.sorry you meant that for Z3to!

**Comment by redruff** [comment]
Well that did it! At least on my Mac at home! Will try the release version on Winblows machine at work tomorrow! Man that was painful! LOL..
Thanks you two!
Red

**Comment by khair-eddine** [comment]
well good for you, i didn't know about the modification :)

**Comment by redruff** [comment]
me either! LOL
thanks again for the replies!

**Comment by z3t0** [comment]
@khair-eddine @redruff The development workflow we are using now is that we develop the code on the master branch and then release them when things are relatively stable. I am thinking of alternatives because this is not too effective since we do not have the equipment to test some of the changes (like adding new protocols) and so development is slowed.

**Comment by z3t0** [comment]
Also, the guides on Sparkfun and other websites have not been updated... I have contacted @SparkFun but they dont seem to be responding

**Comment by redruff** [comment]
yep, I went to a couple other websites looking for alternatives, it was all the same.
As a rookie, the examples tend to be pretty solid, so I was a little flummoxed with this one!

**Comment by z3t0** [comment]
@redruff Yep, the main reason this one is different is that devs tend to create protocols for something like a LG Remote from documentation and submit the code and then the problem is that the people maintaining the project (like me) usually do not have the required equipment to test with (like lg tv) and so the development in this is not a straight line but one that is crooked.

**Comment by z3t0** [comment]
@redruff  use a backtick for code. I'll edit your response above to show you what i mean.

**Comment by z3t0** [comment]
@khair-eddine Both actually. As soon as I get my TV working with IR-Remote I am working on a guide to adding new protocols so we can make it easier for junior devs to help as well.

**Comment by khair-eddine** [comment]
@z3t0 yes bro the problem is multiple transmission and multiple reception because multiple reception works alone well and multiple emission works like a charm (at least for me) but the problem is when we use multiple reception with irsend.
