### ISSUE TITLE
Error: unexpected unqualified-id before '.' token

### ISSUE THREAD

**Issue by Luukth** [shirriff/Arduino-IRremote#165]
Error:
```
error: expected unqualified-id before '.' token
```
```c
Code:
#include <IRremote.h>

IRsend irsend;

void setup() {
}

void loop() {
  IRsend.sendSony(1,1);
}
```

**Comment by AnalysIR** [comment]
irsend.sendSony(1,1);

lower case "irsend" & your include statement is incorrect. The (1,1) is also not a standard set of values for SONY signals.  Unless you have very special requirements, please try to make use of & follow the examples provided with the library.

**Comment by z3t0** [comment]
@AnalysIR has solved this issue by providing a fix. @Luukth If this has not solved your problem please re-open this issue, if a new problem arises create a new issue.
