### ISSUE TITLE
Arduino nano

### ISSUE THREAD

**Issue by MeantCoder** [shirriff/Arduino-IRremote#170]
Hi,

I try teeny LC but not work and I change board Arduino Nano but what connect pin for transmitter?

Thanks..
(Sorry for bad english)

**Comment by AnalysIR** [comment]
Digital pin 3 is the default on the nano

**Comment by MeantCoder** [comment]
Thanks, I'm newbie Arduino :)

**Comment by z3t0** [comment]
@MeantCoder Teensy LC is now supported for receiving (sending is untested and unlikely to work). check #107
