### ISSUE TITLE
Arduino Uno and port 3

### ISSUE THREAD

**Issue by mdymel** [shirriff/Arduino-IRremote#18]
Port 3 is used for sending IR codes. In my sketch, I use it for different purposes and need it as PWM port. IRremote shouldn't use this port if it's not needed. 

After calling irrecv.enableIRIn(); analogWrite works only for HIGH or LOW values.

**Comment by z3t0** [comment]
I will see what I can do and agree that it should not be used if the port is not needed. Can you please retest this to see if this problem is still existent?

**Comment by Marsfan** [comment]
@z3t0 sorry. I have been very busy. I plan to test this over the weekend.

**Comment by z3t0** [comment]
@Marsfan @mdymel Check https://github.com/khair-eddine/Arduino-IRremote/pull/1/files
The pins are being changed there.

**Comment by z3t0** [comment]
@Marsfan Please let me know if you still need help, for now I will be closing this issue
