### ISSUE TITLE
Vizio Compatability

### ISSUE THREAD

**Issue by Hackmodford** [shirriff/Arduino-IRremote#24]
Does this library work with the Vizio remotes? I can't seem to get anything coherent to be read. It always seems to be random values.

The same thing goes for a Sony remote I have too.

**Comment by z3t0** [comment]
Closed for inactivity

**Comment by Arinerron** [comment]
I am getting the same issue.

**Comment by z3t0** [comment]
Can you provide some data as to how your Vizio works?

**Comment by ElectricRCAircraftGuy** [comment]
If you are using the popular 1838 IR receivers from Ebay, open the .h file and change MARK_EXCESS to 0 and/or TOLERANCE from 25 to 35 or 50. Then try again and report back. These really should be parameters, not defines or constants, in my opinion.
