### ISSUE TITLE
NEC send repeat

### ISSUE THREAD

**Issue by alexandruy2k** [shirriff/Arduino-IRremote#28]
Using the NEC protocol the library can detect repeat codes and marks them as 0xFFFFFFFF, however if I need to send a repeat code I can't get it to work.

tried irsend.sendNEC(REPEAT, 0)
  irsend.sendNEC(REPEAT, 4) 
and  irsend.sendNEC(REPEAT, 32)

but none of these result in the NEC protocol repeat code
Is there a way to do it? If I get a quick hint at how to do it I can write it myself and submit it as a patch

**Comment by z3t0** [comment]
Closed for inactivity. If you have been able to solve this issue please post how you did so, and it will be incorporated into the wiki.

**Comment by BramVader** [comment]
I know this issue is somewhat old, but I found how to send repeat codes:

    unsigned int buf[3];
    buf[0] = 9000;  // Mark 9ms
    buf[1] = 2250;  // Space 2.25ms
    buf[2] = 560;   // Burst
    irsend.sendRaw(buf, 3, 38);

The reason why sendNEC() doesn't work is that normal messages have a 9ms mark followed by a 4.5ms space, followed by 32 mark/space bursts.

**Comment by Galysh** [comment]
I also encountered such a problem
I think you can solve the problem as follows

Use code: irsend.sendNEC (REPEAT, 0) 


void  IRsend::sendNEC (unsigned long data,  int nbits)
{
	// Set IR carrier frequency
	enableIROut(38);
	// Header
	mark(NEC_HDR_MARK);
	**if (nbits == 0) space(NEC_RPT_SPACE);
		else space(NEC_HDR_SPACE);**
	// Data
	for (unsigned long  mask = 1UL << (nbits - 1);  mask;  mask >>= 1) {
		if (data & mask) {
			mark(NEC_BIT_MARK);
			space(NEC_ONE_SPACE);
		} else {
			mark(NEC_BIT_MARK);
			space(NEC_ZERO_SPACE);
		}
	}
	// Footer
	mark(NEC_BIT_MARK);
	space(0);  // Always end with the LED off
}

**Comment by scipilot** [comment]
Both @BramVader and @Galysh are correct in the adjustment to the timing of the headers, but I couldn't get their code to work immediately. 

For the latter, I found sending nbits=0 into the function caused undefined behaviour due to the _negative_ left shift in the setup of the for loop - which should be skipped sending no data. So it was still sending one byte of data which invalidated the repeat command.

I detailed it here:
https://stackoverflow.com/questions/59156677/how-can-shift-left-give-different-results-in-different-functions

The fix for me was to skip the data loop entirely.

```
        // Header
        mark(NEC_HDR_MARK);
	if (data == REPEAT)  space(NEC_RPT_SPACE);
	else {
		space(NEC_HDR_SPACE);
                // Data
		for (unsigned long  mask = 1UL << (nbits - 1);  mask;  mask >>= 1) {
	
```

Perhaps I should open a new issue and submit a PR?

**Comment by DrMixe** [comment]
Wonderf

> I know this issue is somewhat old, but I found how to send repeat codes:
> 
> ```
> unsigned int buf[3];
> buf[0] = 9000;  // Mark 9ms
> buf[1] = 2250;  // Space 2.25ms
> buf[2] = 560;   // Burst
> irsend.sendRaw(buf, 3, 38);
> ```
> 
> The reason why sendNEC() doesn't work is that normal messages have a 9ms mark followed by a 4.5ms space, followed by 32 mark/space bursts.

Wonderful! I had been banging my head against this for some time. Now everything works. Thank you sir!

**Comment by ArminJo** [comment]
Or simply use IrSender.sendNECRepeat() 😀 .
