### ISSUE TITLE
IRsend::space(0) causes 16ms delay

### ISSUE THREAD

**Issue by wilagobler** [shirriff/Arduino-IRremote#29]
The library frequently uses space(0) to turn off transmission at the end of sending. space(0) in turn calls delayMicroseconds(0) which gives a longer delay then expected. See https://github.com/arduino/Arduino/issues/1121

**Comment by z3t0** [comment]
The issue referenced has been resolved, inherently resolving this as well. This was a mistake in the Arduino Software.
