### ISSUE TITLE
Multiple definition of "MATCH" error when running IRtest

### ISSUE THREAD

**Issue by X-Y** [shirriff/Arduino-IRremote#30]
When compiling IRtest example, there's an error "In IRremoteInt.h, Multiple definition of 'MATCH', 'MATCH_MARK' and 'MATCH_SPACE'." The issue can be solved by moving the 3 function definitions from IRremoteInt.h to IRremoteInt.cpp

**Comment by z3t0** [comment]
Fixed in #31
