### ISSUE TITLE
Receiver Decode Hangs after immediate send

### ISSUE THREAD

**Issue by darcwader** [shirriff/Arduino-IRremote#37]
I am trying to send a NEC code after receiving a Raw Code and the next loop decode does not work. 

void loop () {
 if (irrecv.decode(&results)) {//hangs on this line after first sendNEC.
     unsigned long hash = decodeHash(&results);
    if(hash == 0xDAEA83EC) {
      irsend.sendNEC(codeChUp,32);//does not send this
    }
    irrecv.resume(); 
  }
}

idea is to throw away one remote and use unused buttons.

**Comment by z3t0** [comment]
You must call enableIRIN(); after sending to receive.

**Comment by z3t0** [comment]
Closed for inactivity
