### ISSUE TITLE
decode_results filled with erroneous data

### ISSUE THREAD

**Issue by PL76** [shirriff/Arduino-IRremote#38]
I am having an issue with IR receive. I can send IR codes with no issues at all. 
I have output to serial monitor for decode_results and every loop it is filled with erroneous data. It is as if my IR receiver is being flooded from another IR source. I hooked up my scope and it only is sending information when I press my remote. But my remote commands only work about 10% of the time because of the flood condition. Is there anything internal to the arduino that could be causing this data to be populated in decode_results without actually receiving anything from the IR receiver?

**Comment by z3t0** [comment]
Closed for inactivity
