### ISSUE TITLE
NEC_ONE_SPACE value is low

### ISSUE THREAD

**Issue by cannondale** [shirriff/Arduino-IRremote#41]
#define NEC_ONE_SPACE    1600

should be:

#define NEC_ONE_SPACE    1692

Noticed this when comparing signals produced by irsend.sendNEC with actual signals captured from NEC protocol remotes. The one spaces are consistently short.

Some references for the NEC protocol:
	
http://wiki.altium.com/display/ADOH/NEC+Infrared+Transmission+Protocol

http://www.techdesign.be/projects/011/011_waves.htm

http://www.sbprojects.com/knowledge/ir/nec.php

http://read.pudn.com/downloads157/sourcecode/embed/701593/docs/IR%20Formats%202.PDF

There seems to be some variation in the length between the above sources with values ranging From 1680 to 1692. But the current value of 1600 is significantly low.

**Comment by z3t0** [comment]
@cannondale I apologize on behalf of the other collaborators for this delay. I will change it in the code. Thanks for the contribution.

**Comment by AnalysIR** [comment]
FYI: To be 100% exact, it should be 1690 intead of 1692.

**Comment by z3t0** [comment]
@AnalysIR thanks, I'll change that now.

**Comment by AnalysIR** [comment]
Great  - thanks

**Comment by z3t0** [comment]
No problem. Thanks for the correction.
commit 4610e7eb0e9371fcd6756c93489370a110cd06cb
