### ISSUE TITLE
Interrupts and other Libraries

### ISSUE THREAD

**Issue by codexmas** [shirriff/Arduino-IRremote#5]
Hey there, thought I would post on the problem I am having, maybe there is a simple solution?

I am using IRRemote to allow an Arduino Nano(168) to be the remote controller for a device that is controlled Via Serial commands.

I am also using the NewSoftSerial library and when I attempt to send Serial data that has been recieved from one serial port to another serial port (relay debugging) several characters are dropped in a random manner.

If I comment out:
irrecv.enableIRIn();

The serial relay is perfect. I have tried all kinds of baud rates, hardware serial, software serial combos and all result in the same random dropping if the IR lib is enabled.

I have even tried enabling the IRSending, as it disables IR receiving, in the hopes that the interrupt handing might not interfere.

My uneducated guess is that there is some blocking going on that causes this issue. The NewSoftSerial lib uses Timer2 as far as I can tell. I also tried to change the IRremoteInt.h lines so that it would use Timer1 instead, apparently without any change.

I'm pretty new at this, so any help would be great!

Great library by the way, it works fantastically. My main goal is to allow anyone to use this setup to utilize any old remote they have lying around to control a Reprap(Makerbot Cupcake) without a computer. Not needing a matrix keypad simplifies the code quite a lot so I am stoked to try and get this working.

Cheers,
Gord.

**Comment by z3t0** [comment]
Library conflicts should be reported on the arduino issue tracker as well because that's where the problem is in this case.

**Comment by z3t0** [comment]
This issue will be recreated with the Interrupts conflicting with PWM and the __vector_7 fix will be added to the wiki as it is an arduino problem.
