### ISSUE TITLE
IRREMOTE SKETCH CODE ETC!

### ISSUE THREAD

**Issue by JimboRoberson** [shirriff/Arduino-IRremote#52]
Hey, I first would like to say for who ever is going to  help me  I am a rookie at this so please bear with me. I have a strong back ground in Electrical. Been learning micro programming and electronic on my only for the past 3 months. Did a lot of programing in school but not of this kind. So lets get started. 

What I am trying to do is take a remote control that works my TV and get the code so that I can use it to let my ipad or computer control the TV with out the remote. I have an Arduino Uno board that I been working with. I have got to have read and seen everything that's been posted on this topic. I think I have a good understand of how it works but i can't seem to get my sketch loaded on to my arduino. tried many times, it just wont load. i tried another sketch and it loaded just find. I have deleted the arduino  program and reloaded it back on my computer but still the same. 

I go the sketch from John Shriff  and from this [tutor site](http://learn.adafruit.com/ir-sensor/ir-remote-signals).

Any help appreciated.

**Comment by z3t0** [comment]
@JimboRoberson I assume this issue has been resolved? If not please let us know how we can help. It is quite unclear from reading the comments above.
