### ISSUE TITLE
IR LED

### ISSUE THREAD

**Issue by thorphar** [shirriff/Arduino-IRremote#58]
I saw an article on how to use a ir receiver and got some decimal numbers back through the serial line. I used the lib function (((   Serial.println(results.value, DEC);  ))) . How can I emit the same code in dec using a ir led ??

Oh by the way I get a UNKNOWN decode back

**Comment by z3t0** [comment]
@thorphar The issue is being closed as it has been over 3 months since any activity and there does not seem to be any pending question. If the issue is not solved simply reopen it and label as 'New'
