### ISSUE TITLE
Board selection doesn't define symbol __AVR_ATtinyX4__?

### ISSUE THREAD

**Issue by vicatcu** [shirriff/Arduino-IRremote#64]
Not sure why, just tested in Arduino 1.0.5 and had to directly hardcode this #define in the IRremoteInt.h to use the library on an ATtiny84. I had selected "ATtiny84 internal 8MHz clock)" from the Boards menu. Also grepped the entire arduino installation directory for __AVR_ATtinyX4__ and got no hits... is it meant to be automatically configured by the IDE or is the hardcoding the expected way to configure the library?

**Comment by z3t0** [comment]
@vicatcu Issue is being closed as this is a board-specific problem and not a compatibility issue, the board does not have enough memory for this library. This is also a common issue, refer to #104
