### ISSUE TITLE
Transmit LED not sending signal on IRrecord example

### ISSUE THREAD

**Issue by jbakar** [shirriff/Arduino-IRremote#71]
Hi,

When I test the IRrecord example, I'm not able to get the transmit LED working. The receiving works fine. 

Using the same hardware set up, I'm able to transmit signal when I run the IRsendDemo sketch alone. With information obtained from IRrecord, I'am able to replay the signal within the IRsendDemo sketch but not when I use the IRrecord; that supposed to be capable of receiving, buffering the code and transmit the signal for replaying the last signal from buffer. 

FYI, I test the availability of transmit signal using phone camera and I confirmed that I can see the IR signal when I run the IRsendDemo sketch but not from the IRrecord sketch.

Regards,
Johan

**Comment by z3t0** [comment]
@jbakar Have you been able to fix this yet?

**Comment by z3t0** [comment]
Closed for inactivity.
