### ISSUE TITLE
Ethernet stops working

### ISSUE THREAD

**Issue by ChinLeongTan** [shirriff/Arduino-IRremote#72]
Hi, I am using the “JVCPanasonicSendDemo” code with an Arduino Uno and Ethernet shield as a web server, it seems to me that “IRremote.h” has somehow stopped the Ethernet from working properly.
Would anyone kind enough to advise? Thank you in adv.

**Comment by ipa64** [comment]
Hi, did you solved your problem? I have the same issue.

**Comment by ipa64** [comment]
Ok, now it's working,  I have to use pin 8 for IR input, then because my application was using 3 PWM outputs 3,5,6 I had to modify to use 5,6,9.

**Comment by z3t0** [comment]
@ChinLeongTan Please close this issue if the problem has been solved. If not please provide more details so we can help.
