### ISSUE TITLE
error compiling on ATmega8

### ISSUE THREAD

**Issue by maxhawkdown** [shirriff/Arduino-IRremote#79]
Dear all,
i try to use IRrecvDemo.ino but it error like below.

../avr/bin/ld.exe: IRrecvDemo.cpp.elf section .text will not fit in region text
/../avr/bin/ld.exe: region text overflowed by 50 bytes

if cause error is overflowed, how can i disable some decode protocol?

**Comment by z3t0** [comment]
@maxhawkdown Please refer to issue #104 as it is likely to yield results.

**Comment by dasarikamalson** [comment]
/avr/bin/ld.exe:MPU6050_DMP6.cpp.elf section .text will not fit in region text
/avr/bin/ld.exe: region text overflowed by 8070 bytes

**Comment by AnalysIR** [comment]
it might help if you open a new issue, with more info.
