### ISSUE TITLE
Casio projector

### ISSUE THREAD

**Issue by modqhx** [shirriff/Arduino-IRremote#87]
Hey great work! Having issues with controlling a Casio projector(green slim)..
So on running the IRrecord or IRRecv sketch, when I press,let's say the "ON" button on the projector's remote, I get --> 
(also printing out out the codeLen turns out to be 20)
`Received NEC: 212F20DF`
`20`
`Received NEC: repeat; ignoring.`

But when I compile the IRSendDemo sketch with same code: projector does not seem to respond--> 

`irsend.sendNEC('212F20DF', 20);`

Any idea why? I'm using about 180 ohm resistor.
I believe NEC commands are sent only once. 

`void loop() {  `
     ` irsend.sendNEC('212F20DF', 20);` 
     ` delay(40000);    `
`}`

**Comment by z3t0** [comment]
@modqhx Please respond if you still need help, otherwise this issue will be closed soon.

**Comment by z3t0** [comment]
Closed for inactivity
