### ISSUE TITLE
Marantz remote

### ISSUE THREAD

**Issue by braice** [shirriff/Arduino-IRremote#88]
Hello

I have a Marantz RC003PM remote which seems to use a special protocol
http://lirc.10951.n7.nabble.com/Marantz-RC5-22-bits-Extend-Data-Word-possible-with-lircd-conf-semantic-td9784.html

Can you give me hints on how to implement it in the Arduino IRremote librairy ? I am not (yet) familiar with IR protocols

Thanks

**Comment by z3t0** [comment]
@braice Reading from the forum leaves it unclear whether or not this has been solved. If not please provide more details as to how we can help you.

**Comment by z3t0** [comment]
Closed for inactivity, marked as 'Add to Wiki' so that we can try and implement this feature.

**Comment by swedeback** [comment]
I see this has been closed for about 6 years, but I have implemented support for this 22 bit extended RC5 protocol. It is working well on my Marantz SR6003. If anyone would be interested? (New to GitHub, but I will start reading up on how to pull and push/merge...)

**Comment by phamviethuy** [comment]
@swedeback  can you give me this code?

**Comment by swedeback** [comment]
Hi @phamviethuy!
Sure thing! But please bare with me, since it will take som time drag it out and dust it off. Will get back to you as soon as I can.

**Comment by swedeback** [comment]
Hi!

I´m really sorry, this completely slipped my mind.
Would you still need this code?

BR
swedeback (Erik)

________________________________
Från: phamviethuy ***@***.***>
Skickat: den 8 maj 2021 16:53
Till: Arduino-IRremote/Arduino-IRremote ***@***.***>
Kopia: swedeback ***@***.***>; Mention ***@***.***>
Ämne: Re: [Arduino-IRremote/Arduino-IRremote] Marantz remote (#88)


@swedeback<https://github.com/swedeback> can you give me this code?

**Comment by phamviethuy** [comment]
@swedeback Thank you, I resolved this problem. I wrote rc5x function to send ir signal for Marantz. It seem working well
