### ISSUE TITLE
Arduino Due and IDE 1.5.7

### ISSUE THREAD

**Issue by saulofr** [shirriff/Arduino-IRremote#91]
Hi,

This problem is occurring in IDE 1.5.7 with the arduino Due.

Arduino: 1.5.7 (Windows 8), Placa:"Arduino Due (Programming Port)"

WARNING: library Robot IR Remote claims to run on [avr] architecture(s) and may be incompatible with your current board which runs on [sam] architecture(s).

IRsendDemo.ino:11:1: error: 'IRsend' does not name a type
IRsendDemo.ino: In function 'void loop()':
IRsendDemo.ino:21:7: error: 'irsend' was not declared in this scope

**Comment by z3t0** [comment]
@victornpb solution worked for me. Is this a problem with Arduino Software or a library conflict in this specific case?

**Comment by z3t0** [comment]
This issue is being closed as the fault is with arguing software which has an issue regarding this matter. Please report there.

**Comment by dhrgrg** [comment]
@tytower i have followed yr steps but arduino ide 1.6.1 is not able to recognise the IRremote directory

**Comment by z3t0** [comment]
what errors do you get

**Comment by tytower** [comment]
Current version is 1.6.3 so I've downloaded it and will have a look

On Tue, 14 Apr 2015 05:27:55 -0700
dhrgrg <notifications@github.com> wrote:

> @tytower i have followed yr steps but arduino ide 1.6.1 is not able to recognise the IRremote directory
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/shirriff/Arduino-IRremote/issues/91#issuecomment-92792470


-- 
Yahoo <tytower@yahoo.com>

**Comment by tytower** [comment]
The issue remains the same . You must delete "Robot IR Remote" library and install https://github.com/shirriff/Arduino-IRremote.

"Multiple libraries were found for "IRremote.h"
 Used: /opt/arduino-1.6.3/libraries/RobotIRremote
 Not used: /opt/arduino-1.6.3/libraries/Arduino-IRremote-master
Error compiling."

-------------------------------------------------------------


On Tue, 14 Apr 2015 05:27:55 -0700
dhrgrg <notifications@github.com> wrote:

> @tytower i have followed yr steps but arduino ide 1.6.1 is not able to recognise the IRremote directory
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/shirriff/Arduino-IRremote/issues/91#issuecomment-92792470


-- 
Yahoo <tytower@yahoo.com>

**Comment by z3t0** [comment]
First rename the downloaded libraty to IRremote then delete RobotIRRemote

--
Thanks,
Rafi Khan 

----- Reply message -----

**Comment by z3t0** [comment]
@tytower did it work?

**Comment by tytower** [comment]
Are you on something The fix was suggested by me

**Comment by z3t0** [comment]
Oh sorry about that

--
Thanks,
Rafi Khan 

----- Reply message -----

**Comment by jenniferrr** [comment]
hi i removed the RobotIRremote library but i didn't install IRRemote from GITHub and i had this:
compiling sketch...
java.lang.NullPointerException
	at processing.app.debug.Compiler.recursiveCompileFilesInFolder(Compiler.java:682)
	at processing.app.debug.Compiler.compileLibrary(Compiler.java:661)
	at processing.app.debug.Compiler.compileLibraries(Compiler.java:649)
	at processing.app.debug.Compiler.compile(Compiler.java:131)
	at processing.app.Sketch.build(Sketch.java:1589)
	at processing.app.Sketch.build(Sketch.java:1509)
	at processing.app.Editor$DefaultRunHandler.run(Editor.java:1915)
	at java.lang.Thread.run(Unknown Source)

what can i do to solve it?

**Comment by z3t0** [comment]
@jenniferrr I don't think that is a problem with the library, please re-install the Arduino IDE

**Comment by Yansley** [comment]
Hello,

I am completely new to Arduino etc. I have a robot car made with an Arduino Uno and my software is the last version available. 

I am trying to control the robot car with an IR remote but I am having the message:

Used: /Users/DonRosa/Documents/Arduino/libraries/IRremote
 Not used: /Applications/Arduino.app/Contents/Java/libraries/RobotIRremote
exit status 1
'TKD2' was not declared in this scope
 I have tried some of the solutions in this conversation but still not compiling.

If you have any working solution please help.
I am running OSX idk if it matters.

**Comment by z3t0** [comment]
Check the other issue you posted on #431
