### ISSUE TITLE
Bug on Atmega8 Fix

### ISSUE THREAD

**Issue by SuperFabius** [shirriff/Arduino-IRremote#96]
Making a simple IR code sender using IRremote library, an IR led and an Atmega8, I noticed a problem after sending the IR code: all time related commands (like millis(), delay(), etc.) stopped to work.
The same sketch runs without any issue on a Atmega328.

See here the bug explanation and how to fix it:

http://forum.arduino.cc/index.php?topic=277528.0

**Comment by z3t0** [comment]
@SuperFabius This issue will be closed and will be added to the wiki along with the revamping of all the documentation. Thank you very much for this contribution!

**Comment by SuperFabius** [comment]
I'm glad to contribute to the community!

If it is useful to complete the wiki, I can send more details about the simple IR sender (final sketch, hardware schematic, etc... ).

**Comment by z3t0** [comment]
Sounds good, maybe clone the wiki and add any pages necessary
