### ISSUE TITLE
ATtiny85/45 and ATtiny 84/44 support

### ISSUE THREAD

**Issue by Xylynx** [shirriff/Arduino-IRremote#97]
When I try and and compile any sketch utilizing the IRremote for a ATtiny 85/45 or a ATtiny 84/84 get a slew of errors. For both devices the errors are related to the timers. I am using the arduino-tiny cores.

Regards
Nathan

**Comment by z3t0** [comment]
@Xylynx This issue seems to have been solved by manually updating winAVR to the latest version. If there are still questions related to this issue feel free to reopen it.
